package jACBrFramework.interop;

import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;

/**
 * This file was autogenerated by <a
 * href="http://jnaerator.googlecode.com/">JNAerator</a>,<br> a tool written by
 * <a href="http://ochafik.com/">Olivier Chafik</a> that <a
 * href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few
 * opensource projects.</a>.<br> For help, please visit <a
 * href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a
 * href="http://rococoa.dev.java.net/">Rococoa</a>, or <a
 * href="http://jna.dev.java.net/">JNA</a>.
 */
public class ComprovanteNaoFiscalRec extends Structure
{
	/// C type : char[4]

	public byte[] Indice = new byte[4];
	/// C type : char[30]
	public byte[] Descricao = new byte[30];
	public boolean PermiteVinculado;
	/// C type : char[4]
	public byte[] FormaPagamento = new byte[4];
	public double Total;
	public int Contador;

	public ComprovanteNaoFiscalRec()
	{
		super();
	}

	@Override
	protected List<String> getFieldOrder()
	{
		return Arrays.asList("Indice", "Descricao", "PermiteVinculado", "FormaPagamento", "Total", "Contador");
	}

	/**
	 * @param Indice C type : char[4]<br>
	 * @param Descricao C type : char[30]<br>
	 * @param FormaPagamento C type : char[4]
	 */
	public ComprovanteNaoFiscalRec(byte Indice[], byte Descricao[], boolean PermiteVinculado, byte FormaPagamento[], double Total, int Contador)
	{
		super();
		if (Indice.length != this.Indice.length) {
			throw new IllegalArgumentException("Wrong array size !");
		}
		this.Indice = Indice;
		if (Descricao.length != this.Descricao.length) {
			throw new IllegalArgumentException("Wrong array size !");
		}
		this.Descricao = Descricao;
		this.PermiteVinculado = PermiteVinculado;
		if (FormaPagamento.length != this.FormaPagamento.length) {
			throw new IllegalArgumentException("Wrong array size !");
		}
		this.FormaPagamento = FormaPagamento;
		this.Total = Total;
		this.Contador = Contador;

	}

	public static class ByReference extends ComprovanteNaoFiscalRec implements Structure.ByReference
	{
	};

	public static class ByValue extends ComprovanteNaoFiscalRec implements Structure.ByValue
	{
	};
}
