package jACBrFramework.interop;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class DAVsRec extends Structure {
	/// C type : char[14]
	public byte[] Numero = new byte[14];
	public int COO_Cupom;
	public int COO_Dav;
	/// C type : char[31]
	public byte[] Titulo = new byte[31];
	public double Valor;
	public double DtEmissao;
	public DAVsRec() {
		super();
	}
	@Override
	protected List<String> getFieldOrder()
	{
	   return Arrays.asList("Numero", "COO_Cupom", "COO_Dav", "Titulo", "Valor", "DtEmissao");
	}
	/**
	 * @param Numero C type : char[14]<br>
	 * @param Titulo C type : char[31]
	 */
	public DAVsRec(byte Numero[], int COO_Cupom, int COO_Dav, byte Titulo[], double Valor, double DtEmissao) {
		super();
		if (Numero.length != this.Numero.length) 
			throw new IllegalArgumentException("Wrong array size !");
		this.Numero = Numero;
		this.COO_Cupom = COO_Cupom;
		this.COO_Dav = COO_Dav;
		if (Titulo.length != this.Titulo.length) 
			throw new IllegalArgumentException("Wrong array size !");
		this.Titulo = Titulo;
		this.Valor = Valor;
		this.DtEmissao = DtEmissao;
	}
	public static class ByReference extends DAVsRec implements Structure.ByReference {
		
	};
	public static class ByValue extends DAVsRec implements Structure.ByValue {
		
	};
}
