package jACBrFramework.interop;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;

/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class FormaPagamentoRec extends Structure {
	/// C type : char[4]
	public byte[] Indice = new byte[4];
	/// C type : char[30]
	public byte[] Descricao = new byte[30];
	public boolean PermiteVinculado;
	public double Total;
	public double Data;
	/// C type : char[30]
	public byte[] TipoDoc = new byte[30];
	public FormaPagamentoRec() {
		super();
	}
	
	/**
	 * @param Indice C type : char[4]<br>
	 * @param Descricao C type : char[30]<br>
	 * @param TipoDoc C type : char[30]
	 */
	public FormaPagamentoRec(byte Indice[], byte Descricao[], boolean PermiteVinculado, double Total, double Data, byte TipoDoc[]) {
		super();
		if (Indice.length != this.Indice.length) 
			throw new IllegalArgumentException("Wrong array size !");
		this.Indice = Indice;
		if (Descricao.length != this.Descricao.length) 
			throw new IllegalArgumentException("Wrong array size !");
		this.Descricao = Descricao;
		this.PermiteVinculado = PermiteVinculado;
		this.Total = Total;
		this.Data = Data;
		if (TipoDoc.length != this.TipoDoc.length) 
			throw new IllegalArgumentException("Wrong array size !");
		this.TipoDoc = TipoDoc;
	}
	
	@Override
	protected List<String> getFieldOrder()
	{
	   return Arrays.asList("Indice", "Descricao", "PermiteVinculado", "Total", "Data", "TipoDoc");
	}
	
	public static class ByReference extends FormaPagamentoRec implements Structure.ByReference {
		
	};
	public static class ByValue extends FormaPagamentoRec implements Structure.ByValue {
		
	};
}
